"""empty message

Revision ID: 5429ff1f6d42
Revises: ce9c39c907c
Create Date: 2014-11-12 11:43:57.548681

"""

# revision identifiers, used by Alembic.
revision = '5429ff1f6d42'
down_revision = 'ce9c39c907c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
